"""create daily_bars

Revision ID: f2e8da32cf63
Revises: 
Create Date: 2026-01-02 20:36:57.819376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e8da32cf63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uniq_symbol_date')
    )
    op.create_index(op.f('ix_daily_bars_date'), 'daily_bars', ['date'], unique=False)
    op.create_index(op.f('ix_daily_bars_id'), 'daily_bars', ['id'], unique=False)
    op.create_index(op.f('ix_daily_bars_symbol'), 'daily_bars', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_bars_symbol'), table_name='daily_bars')
    op.drop_index(op.f('ix_daily_bars_id'), table_name='daily_bars')
    op.drop_index(op.f('ix_daily_bars_date'), table_name='daily_bars')
    op.drop_table('daily_bars')
    # ### end Alembic commands ###
